Traceback (most recent call last):
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/zhenchen/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
os.mkdir('new_dir')  # åˆ›å»ºä¸€ä¸ªæ–°ç›®å½•
os.makedirs('parent/child/grandchild')  # é€’å½’åˆ›å»ºç›®å½•
os.rmdir('new_dir')  # åˆ é™¤ç›®å½•ï¼ˆç›®å½•å¿…é¡»ä¸ºç©ºï¼‰
os.removedirs('parent/child/grandchild')  # é€’å½’åˆ é™¤ç©ºç›®å½•
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[47], line 1[0m
[0;32m----> 1[0m [43mos[49m[38;5;241m.[39mmkdir([38;5;124m'[39m[38;5;124mnew_dir[39m[38;5;124m'[39m)  [38;5;66;03m# åˆ›å»ºä¸€ä¸ªæ–°ç›®å½•[39;00m
[1;32m      2[0m os[38;5;241m.[39mmakedirs([38;5;124m'[39m[38;5;124mparent/child/grandchild[39m[38;5;124m'[39m)  [38;5;66;03m# é€’å½’åˆ›å»ºç›®å½•[39;00m
[1;32m      3[0m os[38;5;241m.[39mrmdir([38;5;124m'[39m[38;5;124mnew_dir[39m[38;5;124m'[39m)  [38;5;66;03m# åˆ é™¤ç›®å½•ï¼ˆç›®å½•å¿…é¡»ä¸ºç©ºï¼‰[39;00m

[0;31mNameError[0m: name 'os' is not defined
NameError: name 'os' is not defined

