Traceback (most recent call last):
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/zhenchen/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/zhenchen/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
import os

sys.path.append(os.path.abspath("other_folder"))  # 绝对路径
import module  # 现在可以正常导入

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      4[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend(os[38;5;241m.[39mpath[38;5;241m.[39mabspath([38;5;124m"[39m[38;5;124mother_folder[39m[38;5;124m"[39m))  [38;5;66;03m# 绝对路径[39;00m
[0;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01mmodule[39;00m

[0;31mModuleNotFoundError[0m: No module named 'module'
ModuleNotFoundError: No module named 'module'

